algo = input('Digite Algo: ')
print('O Tipo primitivo dessa variável é: ',type (algo))
print('Só tem Espaços?',algo.isspace())
print('É um Número?',algo.isnumeric())
print('É Alfabético?',algo.isalpha())
print('É Alfanumérico?',algo.isalnum())
print('Está em Maiusculas?',algo.isupper())
print('Está Minuscula?',algo.islower())
print('Está capitalizada?', algo.istitle())
